version: "3.7"
services:
  fastapi:
    container_name: fastapi-django-template-fastapi
    build: ./fastapi
    volumes:
      - ./fastapi:/src
    ports:
      - 8000:8000
      - 8001:8001
    environment:
      DB_NAME: fastapi-django-template
      DB_USER: fastapi
      DB_PASSWORD: fastapi
      DB_HOST: postgres
      DB_PORT: 5432
    env_file:
      - fastapi/fastapi.env
    links:
      - postgres
      - redis
    command: ./scripts/runlocalserver.sh
  redis:
    container_name: fastapi-django-template-redis
    image: redis:7-alpine
    ports:
      - 6379:6379
  celery-worker:
    container_name: fastapi-django-template-celery-worker
    build: ./fastapi
    volumes:
      - ./fastapi:/src
    links:
      - redis
      - postgres
    command: celery -A app.workers.celery:app worker -l info
    environment:
      DB_NAME: fastapi-django-template
      DB_USER: fastapi
      DB_PASSWORD: fastapi
      DB_HOST: postgres
      DB_PORT: 5432
  celery-beat:
    container_name: fastapi-django-template-celery-beat
    build: ./fastapi
    volumes:
      - ./fastapi:/src
    links:
      - redis
      - postgres
    command: celery -A app.workers.celery:app beat -l info
    environment:
      DB_NAME: fastapi-django-template
      DB_USER: fastapi
      DB_PASSWORD: fastapi
      DB_HOST: postgres
      DB_PORT: 5432
  postgres:
    container_name: fastapi-django-template-postgres
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: fastapi
      POSTGRES_PASSWORD: fastapi
      POSTGRES_DB: fastapi-django-template
    ports:
      - 5433:5432

volumes:
  postgres_data:
